### ISSUE TITLE
Annoying horizontal scroll

### ISSUE THREAD

**Issue by yuvadm** [python/pythondotorg#795] opened 2015-07-16 12:34 UTC
The homepage (as well as many others tested) has a few dozen pixels on the right side that overflow and create an annoying horizontal scroll. Tested on latest Firefox on OS X.

![screen shot 2015-07-16 at 15 32 41](https://cloud.githubusercontent.com/assets/315080/8722726/19e8881a-2bd0-11e5-8e2c-7651829c17c8.png)

**Comment by berkerpeksag** [comment] 2015-07-16 14:29
Thanks for the report, Yuval. This is a duplicate of #731.

**Closed as completed by berkerpeksag** 2015-07-16 14:29 UTC

**Comment by yuvadm** [comment] 2015-07-16 16:41
Sorry for the dupe :)
