### ISSUE TITLE
Calendar widget displays using UTC time zone

### ISSUE THREAD

**Issue by holdenweb** [python/pythondotorg#549] opened 2015-01-14 19:27 UTC
From a recent email of M.A. Lemburg: """That's what the entry uses. The calendar widgets and entries
on python.org use UTC as timezone.""". Shouldn't the event be displayed in the time zone of the event venue - even if this means requesting said time zone for each event?

**Comment by malemburg** [comment] 2015-01-14 19:35
On 14.01.2015 20:27, Steve Holden wrote:

> > From a recent email of M.A. Lemburg: """That's what the entry uses. The calendar widgets and entries
> > on python.org use UTC as timezone.""". Shouldn't the event be displayed in the time zone of the event venue - even if this means requesting said time zone for each event?

This would be possible using the TZ IDs available in the iCal feeds.

OTOH, that would also make it more difficult for people trying to
determine the time in their own timezone. UTC avoids this and
since it is displayed all over the event pages, it's hard not to
detect.

I'd say this is low priority.

## 

Marc-Andre Lemburg
eGenix.com

**Comment by frankwiles** [comment] 2015-01-16 11:33
I can see a couple of options that might be useful: 

1) Display both UTC and the local timezone labeled something like "local time US Central/UTC-6"

2) Option for logged in users to set their local time zone and force display to their timezone 

But yeah probably pretty low priority.

**Comment by malemburg** [comment] 2015-02-20 09:23
Ideal would be to display the events in the browser's timezone, but AFAIK, this is difficult to do in a cross-browser way. Short of that, I think option 2) is the best way to do this.

**Comment by berkerpeksag** [comment] 2017-11-22 11:09
This looks like a duplicate of #87.

**Closed as completed by berkerpeksag** 2017-11-22 11:09 UTC
Labels: psf-review, app/events

**Comment by holdenweb** [comment] 2017-12-07 16:32
Yes, it was, Thanks all.
