### ISSUE TITLE
Monospace font isn't monospace on Android on Chrome.

### ISSUE THREAD

**Issue by verhovsky** [python/pythondotorg#1708] opened 2020-12-18 08:57 UTC
If you open https://docs.python.org in Chrome on an Android phone, the code samples are in a sans-serif proportional font.

![Screenshot_20201218-034914](https://user-images.githubusercontent.com/5687998/102595197-38d36a80-40e5-11eb-8b62-8f9688474f31.png)

Currently this is the `font-family` for code tags:

```css
tt, code, pre {
    font-family: monospace, sans-serif;
    font-size: 96.5%;
}
```

`monospace` not working is a longstanding Android Chrome issue, see https://meta.stackexchange.com/questions/230878/code-blocks-dont-show-up-as-monospace-text-on-the-mobile-website-on-android for details. I think you have to specify fonts by name. If you're going to do this, please set Source Code Pro as the first one, it's the best monospace font in my opinion. Or you could use the `font-family` used for code samples on the [CPython homepage](https://www.python.org/):

```css
    font-family: Consolas,'Lucida Console','Liberation Mono','DejaVu Sans Mono','Bitstream Vera Sans Mono','Courier New',monospace,sans-serif;
```

**Smartphone:**
 - Device: Pixel 5
 - OS: Android 11
 - Browser: Chrome 
 - Version: 87.0.4280.101

(Firefox works fine)

**Comment by hugovk** [comment] 2020-12-18 10:30
Duplicate of https://github.com/python/devguide/issues/581, see also https://github.com/python/python-docs-theme/issues/55.

**Comment by verhovsky** [comment] 2021-10-01 21:48
This is finally fixed in Chrome Canary (Chrome 96)

![Screenshot_20211001-154752.png](https://user-images.githubusercontent.com/5687998/135689805-7ff6b0df-1936-4bde-b0cd-be2708e4e0e2.png)

**Comment by hugovk** [comment] 2021-10-02 15:07
Thanks for the update! 

Chrome 96 is in beta Oct 21 - Oct 28 and stable in 45 days (Nov 16). 

https://www.chromestatus.com/features/schedule

**Closed as completed** 2021-10-27 05:53 UTC
