### ISSUE TITLE
Donor List

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#961] opened 2016-07-25 03:20 UTC
Donor list at the bottom does not retrieve names of donors. Done through dinsdale server? Contact Kurt on where to begin fixing this issue.

https://www.python.org/psf/donations/

**Comment by berkerpeksag** [comment] 2016-07-25 03:57
There are already duplicated reports about this: See https://github.com/python/pythondotorg/issues/709 and https://github.com/python/pythondotorg/issues/83.

**Comment by MarkMangoba** [comment] 2016-07-25 20:53
Thanks Berker, i'll check the report out.

**Comment by berkerpeksag** [comment] 2017-07-20 17:21
Closing this as a duplicate of #709 since Marc-Andre and Kurt gave their feedback there. I've also added the location of the data and the script that updates the old donations page there..

**Closed as completed by berkerpeksag** 2017-07-20 17:21 UTC
Labels: content
