### ISSUE TITLE
Mac OS X is still being used instead of macOS.

### ISSUE THREAD

**Issue by mrael2** [python/pythondotorg#1645] opened 2020-10-01 20:16 UTC
**Describe the bug**
The main page, python.org, refers to Mac OS X. The name of the Apple operating system was changed to macOS some time ago. Please change instances of "Mac OS X" to "macOS".

**To Reproduce**
1. Visit https://python.org
2. Scroll down near the bottom of the page to view the "Downloads" menu of choices.
3. Notice that "Mac OS X" is an available link. Please change to "macOS" instead.

**Expected behavior**
All references to the Apple-provided desktop operating system should be "macOS" instead of "Mac OS X."

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.6)
 - Browser: Safari (13.1.2)

**Screenshots**

<img width="173" alt="Screen Shot 2020-10-01 at 2 08 31 PM" src="https://user-images.githubusercontent.com/19505942/94858658-9ca49c00-03f0-11eb-9b07-5eadb504d462.png">

**Comment by hugovk** [comment] 2020-10-01 20:47
Thank you for the report!

This is a duplicate of https://github.com/python/pythondotorg/issues/1254, and PR https://github.com/python/pythondotorg/pull/1516 fixes some of them.

**Comment by Mariatta** [comment] 2020-10-01 22:01
Duplicate of #1254

**Closed as completed by Mariatta** 2020-10-01 22:01 UTC
