### ISSUE TITLE
Detect Windows platform 32bit/64bit automatically

### ISSUE THREAD

**Issue by tinne** [python/pythondotorg#1044] opened 2016-12-25 09:38 UTC
When navigating https://www.python.org/ with a browser, in the main menu fly-out Downloads/Download for Windows it suggests to download the 32 bit version of the current 2.x and 3.x releases (leaving out the information that the buttons provide 32 bit binaries).

Further, https://www.python.org/downloads/ repeats this pattern in its header area "Download the latest version for Windows".

May I suggest that, depending on the User-Agent header, the menu offers 64 bit versions of the interpreter and tools package by default in case the browser suggests it is running on a 64 bit platform?

According to own tests and [useragentstring.com,](http://www.useragentstring.com/pages/useragentstring.php) this should be possible with a regexp like '(WOW|x)64' on at least IE, FF, Chrome and Edge.

(Duplicate of obviously mistargeted [Python tracker entry #29052.](http://bugs.python.org/issue29052))

**Comment by himanshub16** [comment] 2017-02-18 06:27
Hello. I want to start contribution to the community and am willing to fix this. Could you please help me to find the files where the fix has to be applied?
I am familiar with templating and HTML.

**Comment by berkerpeksag** [comment] 2017-09-26 12:51
This is a bit tricky. Client side detection is easy, but we don't store information about 32-bit/64-bit support so we need to guess it by looking at names of the release files.

Current format of the files:

**OSX**

* 32-bit: Mac OS X 32-bit i386/PPC installer
* 64-bit: Mac OS X 64-bit/32-bit installer

**Windows**

* 32-bit: Windows x86 executable installer
* 64-bit: Windows x86-64 executable installer

I don't think adding bunch of `name__contains` lookups would be enough to reliably get correct files.

I assume most of OSes are 64-bit these days so perhaps we should start to set `download_button=True` for 64-bit files. We can add a note for 32-bit users in the supernav like we already did for Windows XP users:

https://github.com/python/pythondotorg/blob/fea2f399557ec32e3b094901692ed110099ebf34/templates/downloads/supernav.html#L14

Another way to solve this would be to add a `platform` field to `ReleaseFile` model but I don't think it's worth to complicate the implementation.

**Comment by berkerpeksag** [comment] 2017-10-13 06:20
This is basically a duplicate of #171.

**Closed as completed by berkerpeksag** 2017-10-13 06:20 UTC
Labels: enhancement, app/downloads

**Comment by SmartManoj** [comment] 2019-06-18 16:22
Why don't we check the architecture using `js` and provide the appropriate version?
Is this not enough to detect? [Detect 64-bit or 32-bit Windows from User Agent or Javascript?](https://stackoverflow.com/a/6866569)

**Comment by SmartManoj** [comment] 2019-06-18 16:29
How did I unassigned  @MarkMangoba

**Comment by Mariatta** [comment] 2019-06-18 16:35
I think it is GitHub bug. Mark is no longer a member of the Python org, so he cannot be assigned issues anymore.
