### ISSUE TITLE
Download Recognition for Microsoft Surface Pro

### ISSUE THREAD

**Issue by evansuva** [python/pythondotorg#874] opened 2016-01-27 22:01 UTC
Its great how the python.org site recognizes the type of incoming machine and provides the appropriate link to download the installer for that machine.

It doesn't work for the Surface 3 Pro (and presumably for other Surface Pros), though, and it is quite disconcerting that the "Download" tab on the top menu completely disappears when viewing python.org from a surface.

In fact, the Windows x86-64 installer works fine on my Surface 3 Pro (which isn't surprising since it is supposed to be able to run any Windows application).

I'm guessing what you are doing was sensible for the early Surface's that could not run any of the Python distributions, but it would be great if this could be updated to recognized Surface Pro's as Windows machines.

**Comment by tjguk** [comment] 2016-01-31 15:51
Hmmm. The relevant Javascript just does a really simple: 

if (navigator.appVersion.indexOf("Win")!=-1)

So presumably whichever browser the Surface is running isn't advertising itself as something containing "Win". Can you find out what window.navigator.appVersion is for your browser, please?

**Comment by tjguk** [comment] 2016-01-31 18:38
I can't reproduce the effect of the "Download" tab disappearing altogether. (I'm not using a Surface but I'm just faking the relevant JS to ignore my browser), Again, though, we'd really want to know what value it's passing along for navigator.appVersion

**Comment by evansuva** [comment] 2016-01-31 18:51
Thanks, tjguk!  I don't have a surface here to check (two students in my class ran into this issue, and I saw this behavior on their machines), but will check this Monday and let you know.

**Comment by evansuva** [comment] 2016-02-01 19:08
"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0"
A bit of a surprise to see "Windows NT" there, but maybe that's what is breaking things?

**Comment by tjguk** [comment] 2016-02-01 20:13
Well that's very strange since the only thing the code checks is the 
presence of the string "Win" somewhere in the AppVersion string.

Could you attach a screenshot of the button bar where the "Downloads" 
button is (or isn't!) when the Surface is used, please?

TJG

**Comment by berkerpeksag** [comment] 2017-09-23 17:04
Thank you for the report. I just created a custom device in Chrome Devtools with the following settings:

* User agent:

  ```
  Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; Touch)
  ```

  Taken from https://msdn.microsoft.com/library/hh920767(v=vs.85).aspx
* Width, height and pixel ratio taken from https://mydevice.io/devices/

And I couldn't reproduce the behavior you described in https://github.com/python/pythondotorg/issues/874#issue-129283961:

![surface](https://user-images.githubusercontent.com/26338/30775301-74618144-a099-11e7-8c24-dd7f7626b7e9.png)

Note that the downloads page (https://www.python.org/downloads/) also correctly detects user agent.

I understand that this might not be enough to reproduce the actual problem, but without more details (screenshot etc.) I'm inclined to close this issue after 1,5 years. We can always reopen it if you could provide more details, thank you!

**Closed as completed by berkerpeksag** 2017-09-23 17:04 UTC
Labels: frontend, app/downloads
