### ISSUE TITLE
/static/img/google-trans.png not found 

### ISSUE THREAD

**Issue by originalankur** [python/pythondotorg#234] opened 2014-03-01 13:47 UTC
Please note that in the local build on /success-stories/ the image google-trans.png is not available.
![success](https://f.cloud.github.com/assets/11364/2301490/f2721634-a147-11e3-9792-a69607e4c066.png)

**Comment by berkerpeksag** [comment] 2015-03-10 11:03
Thanks for the report. This is a duplicate of #106.

**Closed as completed** 2015-03-10 11:03 UTC
Labels: content
