### ISSUE TITLE
https://www.python.org/news/ not updated

### ISSUE THREAD

**Issue by marco-buttu** [python/pythondotorg#1008] opened 2016-09-14 11:58 UTC
The URL https://www.python.org/news/ it is not updated. I suppose because it has been replaced by https://www.python.org/blogs/, so it should be unavailable.

**Comment by berkerpeksag** [comment] 2016-09-14 12:08
Thanks for the report! You're right, it should probably be redirected to `/blog/`. See #807 for a similar discussion. I'm closing this as a duplicate of #807.

**Closed as completed by berkerpeksag** 2016-09-14 12:08 UTC
