### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [python/pythondotorg#1722] opened 2021-01-14 09:17 UTC

**Comment by hugovk** [comment] 2021-01-14 11:39
Duplicate of https://github.com/python/pythondotorg/issues/1278 and https://github.com/python/pythondotorg/issues/1561?

There's a PR: https://github.com/python/pythondotorg/pull/1446

**Comment by tripleee** [comment] 2021-02-01 07:56
Please revert the title change; it just creates extra work for everyone if we have to click open the issue to figure out what it's about.

**Comment by jai-dewani** [comment] 2021-03-02 13:25
Should this issue be closed if we already have 2 duplicate issues and a PR already in review?

**Closed as completed** 2021-03-16 20:26 UTC
