### ISSUE TITLE
URGENT "Python Source Releases" page is scrambled!

### ISSUE THREAD

**Issue by amirrezahh6** [python/pythondotorg#1421] opened 2019-04-14 13:11 UTC
Following page's layout is scrambled:
https://www.python.org/downloads/source/
I tried with different browsers and even with a proxy but the results were same :(

Snapshot:
https://web.archive.org/web/20190414130440/https://www.python.org/downloads/source/

![image](https://user-images.githubusercontent.com/41161689/56093327-cdb8a600-5eb6-11e9-9be8-b39da9f1a2c8.png)

**Comment by berkerpeksag** [comment] 2019-04-18 19:27
Thank you for the report. See #1420 and #1423 for previous reports. We are discussing how to solve this issue in #1426. Closing this as duplicate of #1426.

**Closed as completed by berkerpeksag** 2019-04-18 19:27 UTC
