### ISSUE TITLE
Feedback to PEPs

### ISSUE THREAD

**Issue by guettli** [python/pythondotorg#1775] opened 2021-05-26 07:47 UTC
**Is your feature request related to a problem? Please describe.**

I am looking at https://www.python.org/dev/peps/pep-0582/

And I have several questions. I guess these questions have already been asked and answered. But where can I read about it?

It would be nice, if there would be a simple and clear feedback process.

For example: There is a category for every PEP on https://discuss.python.org/
And on the page of the PEP there is a link to the corresponding category in the forum.

This would make the feedback flow easier:

1. interested user reads the PEP
2. the user has an idea/concern/question
3. user follows the link to the discussions
4. user can see if his idea was already discussed
5. if there was no discussion about the idea yet, he can ask there
6. Owners of the PEP can reply in the forum.
7. user is happy and Python gets better PEPs.

**Comment by Mariatta** [comment] 2021-06-17 19:56
Generally PEPs are posted to python-dev mailing list, and PEP author would start a thread on the mailing list to discuss one specific PEP and request feedback. Certain PEPs have their own discussion channel. Packaging-related PEPs are usually discussed within the distutils mailing list.

Looking in my email archive, it looks like PEP 582 discussions are happening on this Discourse forum https://discuss.python.org/t/pep-582-python-local-packages-directory/963/109

**Comment by Mariatta** [comment] 2021-06-17 20:00
Duplicate of https://github.com/python/peps/issues/1796

**Closed as completed by Mariatta** 2021-06-17 20:00 UTC
