### ISSUE TITLE
docs.python.org is asking for my location

### ISSUE THREAD

**Issue by verhovsky** [python/pythondotorg#1515] opened 2019-10-12 17:38 UTC
Knowing where I live doesn't help you show me documentation.

![Screenshot_20191012-133245](https://user-images.githubusercontent.com/5687998/66705508-88eeba00-ecf5-11e9-92c7-a932bf200e13.png)

**Comment by berkerpeksag** [comment] 2019-12-06 23:10
Thanks. While I cannot reproduce it myself, I think it's worth to ping infra team as it's out of scope for this tracker. I couldn't transfer this issue to https://github.com/python/psf-infra-meta/issues Could you report it there?

**Closed as completed by berkerpeksag** 2019-12-06 23:10 UTC
