### ISSUE TITLE
Add 3.7 version to CI

### ISSUE THREAD

**Issue by endormi** [python/pythondotorg#1472] opened 2019-07-10 12:08 UTC
**Describe the solution you'd like**
Add 3.7 to run CI

**Comment by berkerpeksag** [comment] 2019-07-10 13:59
This is basically a duplicate of #1267.

**Closed as completed by berkerpeksag** 2019-07-10 13:59 UTC

**Comment by berkerpeksag** [comment] 2019-07-10 14:03
(And thank you for the report!)

**Comment by endormi** [comment] 2019-07-10 14:04
Oops, sorry and no problem
