### ISSUE TITLE
Page scrolling issues on iOS

### ISSUE THREAD

**Issue by youtux** [python/pythondotorg#771] opened 2015-06-02 06:37 UTC
I'm not sure if anyone noticed this, but the page scrolling on iOS (specifically 8.1 on the iPhone 5s) is problematic.
To reproduce the bug:
Open python.org using Safari on iOS, scroll down and then scroll up. The window will always jump to the beginning of page, which is very annoying.

**Comment by berkerpeksag** [comment] 2015-06-02 06:47
Thanks for the report. This is a duplicate of #531.

**Comment by youtux** [comment] 2015-06-02 06:48
Oops sorry for that, I didn't see it.

**Closed as completed by berkerpeksag** 2015-06-02 06:47 UTC
