### ISSUE TITLE
Menu drop downs are always open when JavaScript is disabled

### ISSUE THREAD

**Issue by ugultopu** [python/pythondotorg#1284] opened 2018-06-11 22:25 UTC
When JavaScript is disabled, menu drop-downs are always on. Example:

https://www.python.org/downloads/release/python-365

![screen shot 2018-06-11 at 7 23 16 pm](https://user-images.githubusercontent.com/9937444/41260269-29d068de-6dad-11e8-882f-6e82f5f57900.png)

They should appear on hover.

**Comment by berkerpeksag** [comment] 2018-07-06 10:38
Thanks for the report! This is a duplicate of #52. I will change the issue number to #52 in the commit message.

**Closed as completed by berkerpeksag** 2018-07-06 10:38 UTC
