### ISSUE TITLE
Block system calls to prevent malicious script execution and server information leak

### ISSUE THREAD

**Issue by ronsonware** [python/pythondotorg#1035] opened 2016-11-27 10:37 UTC
The new "Interactive shell" in website have the python commands execution possibility. It is cool, but the "subprocess" and "os" libs are not safe.
test:
os.system('ls /')
os.system('cat /etc/passwd')
I don't test "rm" command and don't execute a malicious script because my objective is help. Check please.

**Comment by berkerpeksag** [comment] 2016-12-20 10:23
Thanks for the report. We don't maintain the REPL on python.org. Perhaps @gpjt can give us some information about this?

**Comment by gpjt** [comment] 2016-12-20 11:39
Thanks for the report!  

That's actually all functioning as intended.  The shell runs in a sandbox, so while you can run any command you like, it should be completely safe.  At the worst case, you may be able to trash your own session.

If you can find any way of escaping the sandbox and (for example) seeing other people's sessions, then we'd love to hear about it.

**Comment by berkerpeksag** [comment] 2016-12-22 05:03
As always, thank you for the prompt response @gpjt! I'm closing this for now. We can reopen it if @Ryukuma can find a way to break the sandbox.

**Closed as completed by berkerpeksag** 2016-12-22 05:03 UTC
