### ISSUE TITLE
Too much horizontal space on mobile Safari

### ISSUE THREAD

**Issue by davisagli** [python/pythondotorg#866] opened 2015-12-10 02:57 UTC
On mobile Safari the breadcrumbs force the viewport to be too wide. See one of the PEPs for an example.
![image](https://cloud.githubusercontent.com/assets/49014/11705688/993a861a-9ea6-11e5-9fd5-ca224a8752f4.png)

**Comment by berkerpeksag** [comment] 2015-12-10 12:37
Thanks for the report. I think this is a duplicate of https://github.com/python/pythondotorg/issues/731. Could you confirm?

**Comment by davisagli** [comment] 2015-12-10 19:27
It's not clear to me that it's a duplicate of 731. The problem doesn't occur for me on the homepage; only on pages with long breadcrumbs.

**Closed as completed** 2017-10-14 05:55 UTC

**Comment by davisagli** [comment] 2017-10-14 13:11
Thanks!
