### ISSUE TITLE
Back to top button functionality is not working

### ISSUE THREAD

**Issue by rkmsmurugesan** [python/pythondotorg#1731] opened 2021-02-16 03:57 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ned-deily** [comment] 2021-03-16 20:27
As noted in #1722, this is a duplicate of #1278 and #1561, with a pending PR: #1446

**Closed as completed by ned-deily** 2021-03-16 20:27 UTC
