### ISSUE TITLE
Python2 Docs Show Up First in Search Engines

### ISSUE THREAD

**Issue by Svetlitski** [python/pythondotorg#1619] opened 2020-07-25 23:02 UTC
Now that Python2 is officially EOL, I would like to humbly suggest that it is only appropriate that searching via Google (or any other search engine) for Python documentation should surface Python3 documentation *first*. Numerous common search terms presently surface Python2 documentation first:

Examples:
- [python itertools](https://google.com/search?q=python%20itertools)
- [python heapq](https://google.com/search?q=python%20heapq)
- [python collections](https://google.com/search?q=python%20collections)

While obviously the Python team cannot *directly* modify search engine results, actions such as removing Python2 documentation from search engine indexing via a [robots.txt file](https://www.robotstxt.org/) would seem appropriate. Consider that anyone using Python2 is unlikely to be a new user (by virtue of using the old version), and should not have too much trouble clicking the Python3 link and selecting the appropriate version of the docs from the selector in the top-left corner of the page.  Meanwhile a new user to Python, particularly a new/inexperienced programmer, would likely be confused and/or unaware of which documentation version they should be using. It seems only right to make things easier for the less experienced user, and to simultaneously prioritize users of modern python over those using an **unsupported** version.

**Comment by hugovk** [comment] 2020-07-26 05:44
Thanks for the report. Duplicate of https://github.com/python/pythondotorg/issues/1030?

**Comment by berkerpeksag** [comment] 2020-07-26 07:38
This is indeed a duplicate of #1030. Thank you for the report, Kevin!

**Closed as completed by berkerpeksag** 2020-07-26 07:38 UTC
