### ISSUE TITLE
Empty lists, when using left menu.

### ISSUE THREAD

**Issue by AlexBaranowski** [python/pythondotorg#796] opened 2015-07-24 09:56 UTC
Hello World! I have been surfing around your great website and found bug. My original flow was
index ->clicked on Success Stories ILM -> clicked on left menu bar (Arts,Business,Education..) then list is empty or almost empty.
In the same time upper menu with Success Stories is working fine. Bottom list with Success Stories is also working fine.
My web browser is Firefox 39.
![pythonbug](https://cloud.githubusercontent.com/assets/8447941/8872177/fd34ba28-31fa-11e5-9b72-a7f62b2494b9.png)

**Comment by berkerpeksag** [comment] 2015-07-24 10:04
Thanks for the report, Alex. This looks like a duplicate of https://github.com/python/pythondotorg/issues/69. Also, the pages you've mentioned are two different locations:
- Works fine: https://www.python.org/about/success/#government
- Empty: https://www.python.org/success-stories/category/government/

I think we need to deduplicate these pages.

**Comment by berkerpeksag** [comment] 2017-07-20 17:02
Closing this as a duplicate of #69. We are going to migrate old data into the new /success-stories/ app.

**Closed as completed by berkerpeksag** 2017-07-20 17:02 UTC
Labels: app/success-stories
