### ISSUE TITLE
Identify key problems with community involvement

### ISSUE THREAD

**Issue by techtonik** [python/pythondotorg#902] opened 2016-03-20 17:59 UTC
I don't know statistics about site visits (#901), but a https://github.com/python/pythondotorg/graphs/contributors shows almost a staggering lack of new people contributing to the project.

![image](https://cloud.githubusercontent.com/assets/515889/13905957/96a1aab8-eede-11e5-8883-4fe9bf5eb11d.png)

**Comment by berkerpeksag** [comment] 2016-03-21 11:07
Duplicate of https://github.com/python/pythondotorg/issues/534.

**Closed as completed by berkerpeksag** 2016-03-21 11:07 UTC

**Comment by techtonik** [comment] 2016-03-21 12:56
Oops. I am surprised to see this is a duplicate.

**Comment by techtonik** [comment] 2016-03-21 18:52
@berkerpeksag #534 was just closed, so should we forget about problem?
