### ISSUE TITLE
Display issues with search bar results

### ISSUE THREAD

**Issue by yasinpgt** [python/pythondotorg#1032] opened 2016-11-21 21:03 UTC
when i search for strings like  'about' and 'events' on python.org search bar ( https://www.python.org/search/?q=events&submit=) & (https://www.python.org/search/?q=about&submit=) the rendered page has a number of display issues. Here's a screenshot from Mozilla Firefox.
![python_about_page](https://cloud.githubusercontent.com/assets/23642583/20500566/e970b8a8-b05b-11e6-9a64-01337eca9ade.PNG)
![python_rendrissue](https://cloud.githubusercontent.com/assets/23642583/20500567/e986c922-b05b-11e6-906b-0d698c81b78f.PNG)

**Comment by Mariatta** [comment] 2016-11-21 21:06
Same issue as https://github.com/python/pythondotorg/issues/883, I think.

**Comment by berkerpeksag** [comment] 2016-11-22 07:41
Thanks for the report, yasinpgt. Yes, this is a duplicate of #883.

**Closed as completed by berkerpeksag** 2016-11-22 07:41 UTC
