### ISSUE TITLE
Unnecessary horizontal scrolling and strange empty space on the right

### ISSUE THREAD

**Issue by vitaut** [python/pythondotorg#762] opened 2015-05-24 21:02 UTC
There is unnecessary horizontal scrolling with some empty space to the right when viewing http://python.org in Chrome 43 and, possibly, other versions:

![screenshot from 2015-05-24 13 57 56](https://cloud.githubusercontent.com/assets/576385/7789653/3fa61cde-021d-11e5-8b9b-083f8903a206.png)

**Comment by berkerpeksag** [comment] 2015-05-24 21:36
Thanks for the report. This is a duplicate of #731.

**Closed as completed by berkerpeksag** 2015-05-24 21:36 UTC
