### ISSUE TITLE
Python 2.7.14 Compression Library documentation front page is in Japanese, not English

### ISSUE THREAD

**Issue by japagetw** [python/pythondotorg#1207] opened 2017-12-21 03:30 UTC
https://docs.python.org/2/library/archiving.html is in Japanese.  These are the English documents, so they should be in English.  Linked to pages are all in English, even when the link is in Japanese.

**Comment by JulienPalard** [comment] 2017-12-21 06:07
Thanks for reporting, @japagetw, it's a known issue we were unable to reproduce (https://bugs.python.org/issue31584).

Sadly I don't see it in my side, nor on the servers, so it does not help me to fix it :(

I'll however try an easy fix: https://github.com/python/docsbuild-scripts/issues/35

As a duplicate this issue can be closed.

**Comment by Mariatta** [comment] 2017-12-21 06:12
Hmm I should have taken a screenshot when I saw it :(
It looks fine now.
Thanks @JulienPalard, I'll close this.

**Closed as completed by Mariatta** 2017-12-21 06:12 UTC

**Comment by JulienPalard** [comment] 2017-12-21 06:25
@Mariatta don't worry, I don't need a screenshot to trust an issue. I'd like to see it it my side to check where it happen (physically), to run some greps on the server typically, but anyway using different directories should help, even by fixing it, or by giving a hint it's something else if it still happen.
