### ISSUE TITLE
Search bar breaks layout on focus

### ISSUE THREAD

**Issue by linssen** [python/pythondotorg#102] opened 2014-02-20 12:36 UTC
![search](https://f.cloud.github.com/assets/67624/2218275/9727f7b2-9a2b-11e3-9053-fc9b4bc348a7.gif)

**Comment by frankwiles** [comment] 2015-01-16 12:33
Can't reproduce, closing as it was likely fixed long ago.

**Closed as completed by frankwiles** 2015-01-16 12:33 UTC
Labels: frontend
