### ISSUE TITLE
Page scrolls all the way to the top spontaneously

### ISSUE THREAD

**Issue by oconnor663** [python/pythondotorg#792] opened 2015-07-05 23:03 UTC
Happens on at least https://www.python.org/dev/peps/pep-0492/. I'm on Chrome on Android.

When I scroll up a little bit, some event seems to trigger that scrolls the page all the way up to the top. This is especially annoying on longer pages like the link above.

**Comment by berkerpeksag** [comment] 2015-07-06 03:50
Thanks for the report! This is a duplicate of #531.

**Closed as completed by berkerpeksag** 2015-07-06 03:50 UTC
