### ISSUE TITLE
donors list "being ported to the new website"

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#709] opened 2015-03-24 19:19 UTC
https://www.python.org/psf/donations/#donors
"""
The PSF would like to thank the following donors for their contributions. Donors are listed in descending order using an algorithm that takes into account both the amount of donation and the age of the donation.

```
The donors list is being ported to the new website. Please see our previous donation page for the current list. It gets updated daily. Thank you.
```

"""

**Comment by berkerpeksag** [comment] 2015-03-24 20:28
This is probably a duplicate of #83. I couldn't find the script that creates the donor list in the legacy website repo. If anybody knows how this list can be created, I would be happy to port it.

**Comment by berkerpeksag** [comment] 2015-03-24 20:35
Ok, found it at https://svn.python.org/www/trunk/pydotorg/scripts/get-donors.py

**Comment by malemburg** [comment] 2015-03-24 20:36
There is an attempt underway to integrate the legacy listing into
the new site using an iframe.

I'm not sure how difficult it would be to actually integrate the
logic into the site itself.

## 

Marc-Andre Lemburg
eGenix.com

**Comment by berkerpeksag** [comment] 2015-03-24 20:42
The data file can be found at http://legacy.python.org/psf/donations-data.html but couldn't find how it's created. Perhaps a cron job?

**Comment by berkerpeksag** [comment] 2015-03-24 20:46
> There is an attempt underway to integrate the legacy listing into
> the new site using an iframe.

If the content in https://www.python.org/psf/donations/ comes from the database, I think JSON + a couple line JavaScript would do the job, too.

**Comment by malemburg** [comment] 2015-03-24 20:59
On 24.03.2015 21:42, Berker Peksag wrote:

> The data file can be found at http://legacy.python.org/psf/donations-data.html but couldn't find how it's created. Perhaps a cron job?

Yes, a cronjob. Kurt Kaiser knows the details (CCed).

## 

Marc-Andre Lemburg

**Comment by malemburg** [comment] 2015-03-25 23:20
I was subscribed to the PyDotOrg list, now defunct.  I'll subscribe to
pythondotorg when I get back to my workstation Friday.  I don't expect
to be able to do anything about this issue until after PyCon - maybe at
the Sprints, if I'm lucky.

There is a cron on my end which processes the donor list into an html
fragment and uploads it to dinsdale.  Then, there is a general cron on
dinsdale which periodically refreshes the site and includes the fragment
into a formatted page.

I can provide the data in any useful form - html, plain text, etc.  It's
just a list of names, processed through the famous Tim Peters
declining algorithm ("donate early, donate often").  I can push it or
you can pull it.

Thanks for the cc:

KBK

**Comment by hugovk** [comment] 2024-09-04 20:08
I believe this is now fixed.

**Closed as completed by hugovk** 2024-09-04 20:08 UTC

**Comment by ezio-melotti** [comment] 2024-09-05 08:42
I noticed that in https://www.python.org/psf/donations/#donors there are 4820 donors, whereas at https://legacy.python.org/psf/donations-data.html there are 5923.
Is this intentional or should I create a new issue?

**Comment by malemburg** [comment] 2024-09-05 09:02
I don't think the legacy site version gets updated anymore. You can that the entries from the old listing have moved down the ranking; that's how the list works and shows that more recent entries are at the top.

**Comment by ezio-melotti** [comment] 2024-09-05 09:39
The current page is missing 1103 names that were listed in the legacy page.
I would expect the current page to have all the old names, plus any new donor that donated after the legacy page stopped being updated.

**Comment by hugovk** [comment] 2024-09-05 10:01
@ezio-melotti I think it's best to create a new issue, and can you ping `@indepndnt` in it?

**Comment by ezio-melotti** [comment] 2024-09-05 10:12
Done!
