### ISSUE TITLE
Job submission leaves you on a page showing the job

### ISSUE THREAD

**Issue by gpjt** [python/pythondotorg#300] opened 2014-03-14 13:57 UTC
...not on the "Thanks for submitting" page.  If you're logged in to the site as an admin, you also get a place to leave a comment on the job too, which is doubly confusing, but unlikely to happen frequently IRL.

**Comment by ubernostrum** [comment] 2015-03-06 03:20
This is probably a good easy-pickings bug for sprinting on.

**Comment by berkerpeksag** [comment] 2015-03-15 19:05
This is a sort of duplicate of #600 and has been fixed recently. Closing for now.

**Closed as completed by berkerpeksag** 2015-03-15 19:05 UTC
Labels: backend, easy, app/jobs
