### ISSUE TITLE
Look and Feel 

### ISSUE THREAD

**Issue by santoshwebonise** [python/pythondotorg#772] opened 2015-06-02 06:53 UTC
Hi Team,

I noticed that your website showing a horizontal scroll bar at bottom-right of the page, my screen resolution is 1280 x 800, which is standard resolution.
A website should be looks perfect in the resolution of 1024 x 600 (onward).

Note : It also look prefect in mobile if you make it responsive

See the attached image.
![untitled](https://cloud.githubusercontent.com/assets/3865183/7929966/79c2a594-0921-11e5-9a85-463171d13ada.png)

Regards,
Santosh Biswakarma
santoshbiswakarma@gmail.com

**Comment by berkerpeksag** [comment] 2015-06-02 06:58
Thanks for the report. This is a duplicate of #731.

**Closed as completed by berkerpeksag** 2015-06-02 06:58 UTC
