### ISSUE TITLE
502 when submitting/saving a job

### ISSUE THREAD

**Issue by Hannahmc8** [python/pythondotorg#669] opened 2015-03-18 16:54 UTC

**Comment by malemburg** [comment] 2015-03-18 17:25
This is likely caused by the issue #652.

**Comment by malemburg** [comment] 2015-03-18 17:27
If you run into this problem, please check your descriptions in an online ReST editor such as http://rst.ninjs.org/

**Comment by Hannahmc8** [comment] 2015-03-18 18:55
Thanks Marc, I'm not one of the techies at our firm so will be at sea I guess!

Hannah McIntyre

Founder | CrunchBoards 
Brighton, UK
Fast, effortless, beautiful. Transform your accounts package into Financial Intelligence. Show me how!
Sent from my iPhone

On 18 Mar 2015, at 17:27, Marc-Andre Lemburg notifications@github.com wrote:

If you run into this problem, please check your descriptions in an online ReST editor such as http://rst.ninjs.org/

**Comment by malemburg** [comment] 2015-03-18 19:23
On 18.03.2015 19:55, Hannahmc8 wrote:

> Thanks Marc, I'm not one of the techies at our firm so will be at sea I guess!

Could you perhaps post the descriptions here ? Then we can check them.

## Thanks,

Marc-Andre Lemburg

**Comment by berkerpeksag** [comment] 2015-09-29 20:45
https://github.com/python/pythondotorg/blob/master/docutils.conf is likely fixed this issue, too. Can we close this now?

**Comment by malemburg** [comment] 2015-09-29 20:46
Yes. Thanks, Berker.

**Closed as completed by malemburg** 2015-09-29 20:46 UTC
Labels: app/jobs
