### ISSUE TITLE
Success Stories throws an 503 Error

### ISSUE THREAD

**Issue by mmshivesh** [python/pythondotorg#1310] opened 2018-08-10 17:48 UTC
**Bug Description**
Going to https://www.python.org/success-stories/ throws a Error 503

**To Reproduce**
1. Go to https://www.python.org/success-stories/
2. See Error 503 No healthy backends

**Expected behavior**
A page with success stories of the Python language is supposed to appear (?)

**Screenshots**
![Error 503](https://user-images.githubusercontent.com/23611514/43972876-71f5c4ae-9cf3-11e8-8e37-78a1395de767.png)

**Desktop:**
 - OS: macOS High Sierra
 - Safari
 - v11.1.2

**Comment by Mariatta** [comment] 2018-08-10 17:52
Duplicate of #1309

**Closed as completed** 2018-08-10 17:57 UTC
