### ISSUE TITLE
Success stories - Category: Art; appears empty

### ISSUE THREAD

**Issue by Yan9080** [python/pythondotorg#1558] opened 2020-02-23 15:51 UTC
**Describe the bug**
Category Art from Success stories appears empty or blank.

**To Reproduce**
1. Go to 'https://www.python.org/'
2. Click on 'Success Stories' then 'Arts'
4. See error: The page only shows the 'Art' category title but nothing else.

**Expected behavior**
It should shows related links about the art success stories.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 Service Pack 1
 - Browser:  chrome
 - Version: chrome 79.0.3945.130

**Smartphone (please complete the following information):**
I haven't checked with my mobile device

**Additional context**
I don't know if this behavior is expected but anyhow I decided to report it. 
Kind regards.

**Comment by pyfisch** [comment] 2021-02-28 17:57
Still empty.

**Comment by hugovk** [comment] 2024-09-05 17:41
Thanks for the report, closing as a duplicate of https://github.com/python/pythondotorg/issues/2051 (that one's actually newer, but also has an offer of writing something up).

**Closed as not planned by hugovk** 2024-09-05 17:41 UTC
