### ISSUE TITLE
Events calendar entries in search results have wrong URLs

### ISSUE THREAD

**Issue by chrullrich** [python/pythondotorg#933] opened 2016-04-20 13:30 UTC
When searching for "calendar" using the main search box, the first two results are "Calendar - Python Events Calendar" and "Calendar - Python User Group Calendar". Both of these have broken links:

```
<h3>Calendar – <a href="//events/python-events/">Python Events Calendar</a></h3>
<h3>Calendar – <a href="//events/python-user-group/">Python User Group Calendar</a></h3>
```

Note the double slash turning a relative into a protocol-relative URL.

**Comment by berkerpeksag** [comment] 2016-04-20 13:38
Thanks for the report. This is a duplicate of #883. I will try to make some time to fix it this week.

**Closed as completed by berkerpeksag** 2016-04-20 13:38 UTC
