### ISSUE TITLE
mobile site constantly scrolls to top

### ISSUE THREAD

**Issue by richardsheridan** [python/pythondotorg#761] opened 2015-05-22 02:50 UTC
Chrome 42.0.2311.111 reading any PEP is impossible because I keep getting pulled up to the top of the page. This has been going on a while but I am finally fed up!

I can't always trigger it, but it seems to happen when scrolling up/sweeping down.

**Comment by berkerpeksag** [comment] 2015-05-22 13:09
Thanks for the report! This is a duplicate of #531. I'll take a look at it in a couple of weeks.

**Closed as completed by berkerpeksag** 2015-05-22 13:09 UTC
Labels: frontend
