### ISSUE TITLE
All Directory open bug

### ISSUE THREAD

**Issue by MDRazwanul** [python/pythondotorg#1376] opened 2019-01-17 04:11 UTC
Hello Anyone can download all the information which you all uploaded here. Please fix it ASAP. 
Prove https://www.python.org/ftp/python/
![screenshot_193](https://user-images.githubusercontent.com/38924783/51295096-30c5a880-1a40-11e9-8fa2-b80a8715c9e3.png)

**Comment by Mariatta** [comment] 2019-01-17 04:46
Sorry, what is the problem in your opinion?
Python has always been available for free and open source.
Those are the files linked from python.org/downloads

**Comment by berkerpeksag** [comment] 2019-01-17 08:30
This is a duplicate of #767. Please see that issue for more details.

**Closed as completed by berkerpeksag** 2019-01-17 08:30 UTC
